/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"
#include "BankAccount.h"
#include "Menu.h"

int main()
{
    return Menu(BankAccountService(BankAccountRepo())).run();
}
